### PR TITLE
some tidy up and compilation fixes.

### PR DESCRIPTION
**Pull request by dirvine**
Some commented code here, which was already unimplemented (after unimplemented block).  Also some slight changes to travis to allow run on container and added clippy as feature to allow run form command line, perhaps easier.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0a9d78e49cf610bf39af6730df9fc21e9547b3d0
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 8eb1efdfd1103202bb51d142320774cd7b77e2b5
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: d09193535e4735bb40835c05ecab60caa40fd8c4
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: f80e66eac595d61a580cad346e375419340aadd7
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: e48778a7a7677da16c1013af092068af13f47661
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by hobofan** [comment]
Thanks :) I am sorry but a lot of the code changes will fall away once I bring most of the code for 0.2 upstream. The changes to travis/clippy look good however and I'd like to merge them.

Could you please squash the commits to a single one and give it a commit message according to our [contribution guide](https://github.com/autumnai/leaf/blob/26af7415f0fe5e843aee11cc55db34370b244d9e/CONTRIBUTING.md#commit-message-format)?

**Comment by dirvine** [comment]
No problem I will do and of course document properly (style perhaps). Do you want only the travis / clippy parts? Happy to remove the rest of the changes as I was not happy with them anyhow. Happy you use neat guidelines and keep documentation tidy. We will do the same soon I hope.

**Comment by hobofan** [comment]
Yeah, I think only travis / clippy would be better then, as it keeps the commit more focused.

**Comment by dirvine** [comment]
Closing to re-submit from clean master

**Pull request closed without merging**
