### PR TITLE
style/travis: Allow travis to build on container based system

### PR DESCRIPTION
**Pull request by dirvine**
Added required apt-packages
Added ability to run clippy as feature in nightly
set sudo false in travis

Several remaining compile fixes remain, but will be resolved with upcoming
fix with 0.2 code.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ef5808f074cade0987dca3566edb4b07ac6df2f9
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by dirvine** [comment]
Is it possible to have some examples of the commit message format? I see you use "style/XXX" where XX is changed file or module. I am not sure if this is what is missing, sorry for any miscommunication here. I Will also dig more into gitcop to see what I can find.

**Comment by hobofan** [comment]
I see you have figured it out, but you are right, having an example in the guidelines would certainly be nice (issue #48).

Since I saw that #46 passed with the other changes I will go ahead and merge it even though it's failing.

Thanks you! :)

**Comment by hobofan** [comment]
Oh :open_mouth:, only the PR title had the correct format, not the commit. Oh well...

**Comment by dirvine** [comment]
Ah yes I spotted that just after the merge. Oh well not to worry. Sorry chap, I ended up rebasing (hard) locally and could not get back to the commit. At least I now know. Next time though it will all be good.

**Comment by hobofan** [comment]
Yup, better luck next time :)

**Pull request merged**
