### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by kschmit90**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2843c971b107e2ad4f8bf387df46a4ea46e229bc
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by hobofan** [comment]
Thank you! :+1:

**Comment by hobofan** [comment]
@homu r+

**Comment by hobofan** [comment]
Sorry, I was a bit too hasty with merging the PR.

The edits are great but please take a look at our [Contribution Guide](https://github.com/autumnai/leaf/blob/cbfbc3e1cd092f0714ff3576ca750305fcaadb36/CONTRIBUTING.md).

I manually ammended the commit message(cbfbc3e1cd092f0714ff3576ca750305fcaadb36) and all is good now. :wink:

**Pull request merged**
