### PR TITLE
Fixed typo: crucial from curcial

### PR DESCRIPTION
**Pull request by palerdot**
Changed typo from word curcial to **crucial**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a5537c7f296d1fcf18642736ed8588d0347a75b5
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by palerdot** [comment]
@GitCop I couldn't find the guidelines in the mentioned url

**Comment by hobofan** [comment]
@palerdot Thanks for the contribution! :+1: 
The correct link is this one: <https://github.com/autumnai/leaf/blob/master/CONTRIBUTING.md#git-commit-guidelines>

A fitting commit message for your commit would be `docs/readme: crucial from curcial`. The body of the commit message can stay the same.

**Comment by palerdot** [comment]
Thanks. will do from now on.

**Comment by hobofan** [comment]
Could you please also amend the commit message of this PR? :wink:

**Comment by palerdot** [comment]
Amended. Was that Ok ?

**Comment by hobofan** [comment]
Yes the commit message looks good now! :)

Due to some reasons Travis CI doesn't run the tests, but I think that's something I'll have to fix on our side.

**Comment by hobofan** [comment]
Oh, damn, sorry for not noticing earlier. You fixed the problem in the `gh-pages` branch. However the `gh-pages` branch just contains documentation that will be regenerated after every push to `master`. So if I would merge the PR right now the change would disapear very soon.

The actual origin of the generated documentation would be here:
https://github.com/autumnai/leaf/blob/master/src/lib.rs#L59

**Comment by palerdot** [comment]
I just gave another pull request to master branch with the required commit format.
https://github.com/autumnai/leaf/pull/83

**Pull request closed without merging**
