### PR TITLE
docs/everything: add documentation guidelines and apply it to the whole library

### LINKED ISSUE #13: improving documentation for easier engagement
I came across some inconsistencies in our documentation - especially in its quality. On the one side, we are not documenting the complex parts, which makes it hard to contribute, because one isn't really getting what the code does and on the other side, we are documenting quite obvious things.

A lot of the other Deep/Machine Learning Frameworks aren't really better at documentation, but I think it is quite important to make documentation a num.1 priority, because the underlying technology is not really broadly understood and under heavy change. Meaning that we have to address two personas with our documentation:

- those who want to use `Leaf`
- those who would like to develop on `Leaf`

I experienced those problems myself when I was working on the conv layers and think it is quite important to remove the obstacles to contribution and usage due to unsufficient documentation right now - as they become only harder to remove the further on we move.

I will express my thoughts and propose a solution to that problem later in the day.

### PR DESCRIPTION
**Pull request by hobofan**
CLOSES #13

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0f5cc1faadc35c4fd30d6dae61ae9aa51cefb614
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 38c7cfb65807deb4a5da2b28f6a5fdb593c9d412
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: edfbbdfb3c262782fe3859c40315250394161957
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 7aa05dd2c5f3c257d92cb284a14abda0a59c488e
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 05580fc9f7744321c0ea485387f1e0234a7704a8
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: a26e885ddfccd3f683be813911562032273751b9
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by MichaelHirn** [comment]
Not acceptable. There are a lot of crucial parts missing. We need at least the following, in order to close this PR.

* [ ] A high-level description of the Layer module (about it's architecture). Take a look to at the layers or network module
* [ ] A high-level description for the Solver module.
* [ ] A high-level description for the Solvers module ->  similar to layers module.
* [ ] Move Glossary from network to crate page.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0f5cc1faadc35c4fd30d6dae61ae9aa51cefb614
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 38c7cfb65807deb4a5da2b28f6a5fdb593c9d412
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: edfbbdfb3c262782fe3859c40315250394161957
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 7aa05dd2c5f3c257d92cb284a14abda0a59c488e
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 05580fc9f7744321c0ea485387f1e0234a7704a8
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: a26e885ddfccd3f683be813911562032273751b9
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0f5cc1faadc35c4fd30d6dae61ae9aa51cefb614
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 38c7cfb65807deb4a5da2b28f6a5fdb593c9d412
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: edfbbdfb3c262782fe3859c40315250394161957
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 7aa05dd2c5f3c257d92cb284a14abda0a59c488e
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 05580fc9f7744321c0ea485387f1e0234a7704a8
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: a26e885ddfccd3f683be813911562032273751b9
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0f5cc1faadc35c4fd30d6dae61ae9aa51cefb614
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 38c7cfb65807deb4a5da2b28f6a5fdb593c9d412
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: edfbbdfb3c262782fe3859c40315250394161957
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 7aa05dd2c5f3c257d92cb284a14abda0a59c488e
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 05580fc9f7744321c0ea485387f1e0234a7704a8
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: a26e885ddfccd3f683be813911562032273751b9
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 83db20d4540240aaa8c0031bd8b67ae4d6e4c264
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0f5cc1faadc35c4fd30d6dae61ae9aa51cefb614
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 38c7cfb65807deb4a5da2b28f6a5fdb593c9d412
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: edfbbdfb3c262782fe3859c40315250394161957
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 7aa05dd2c5f3c257d92cb284a14abda0a59c488e
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 05580fc9f7744321c0ea485387f1e0234a7704a8
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: a26e885ddfccd3f683be813911562032273751b9
  * Commits must be in the following format: **%{type}/%{scope}: %{description}**

 * Commit: 83db20d4540240aaa8c0031bd8b67ae4d6e4c264
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/autumnai/leaf/blob/develop/CONTRIBUTING.md#git-commit-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by hobofan** [comment]
@homu r+

**Pull request merged**
