### PR TITLE
feat/serialization: add serialization

### LINKED ISSUE #14: load network with weights from file
The only way for the moment to create Networks is by specifying a new Network with a [`NetworkConfig`][1], which means the Network gets initialized from scratch.

Resuming to already trained models and keeping the learning state-less with loading from raw weights would open new usage scenarios.

We are looking forward to use [Cap'n Proto][2] for serialization, as it allows for state-of-the-art performance.

[1]: http://autumnai.github.io/leaf/leaf/network/struct.NetworkConfig.html
[2]: https://capnproto.org/

### PR DESCRIPTION
**Pull request by hobofan**
WIP, the commit for deserialization is still missing because it needs a bit of polish

Will resolve #14, #15

### CODE REVIEW

**Comment by hobofan** [comment]
@MichaelHirn :)

**Comment by MichaelHirn** [comment]
Thank you, @hobofan 

Are now all layers serializable? Also could you add a test/example of the serializing/deserializing a network?

**Comment by hobofan** [comment]
@MichaelHirn All layers are serializable, and I added a basic test of saving and loading, and a example for each.

**Comment by MichaelHirn** [comment]
LGTM. Thank you for the update. Ready to merge

**Comment by MichaelHirn** [comment]
@homu r+

**Pull request merged**
